---

- name: Modprobe br_netfilter
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "br_netfilter"
    - "iptable_nat"

- name: Modprobe IPVS
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "ip_vs"
    - "ip_vs_rr"
    - "ip_vs_wrr"
    - "ip_vs_sh"
    - "nf_conntrack_ipv4"
  when: NET_MODE == 'ipvs' | default(false)

- name: Load Module
  template:
    src: k8s.j2
    dest: /etc/modules-load.d/k8s.conf

- name: Check Sysctl
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes ignoreerrors=yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: 1 }
    - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { name: "kernel.sem", value: "250 32000 32 1024" }
    - { name: "net.core.netdev_max_backlog", value: 20000 }
    - { name: "net.core.rmem_default", value: 262144 }
    - { name: "net.core.rmem_max", value: 16777216 }
    - { name: "net.core.somaxconn", value: 2048 }
    - { name: "net.core.wmem_default", value: 262144 }
    - { name: "net.core.wmem_max", value: 16777216 }
    - { name: "net.ipv4.tcp_fin_timeout", value: 15 }
    - { name: "net.ipv4.tcp_max_orphans", value: 131072 }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 16384 }
    - { name: "net.ipv4.tcp_mem", value: "786432 2097152 3145728" }
    - { name: "net.ipv4.tcp_tw_reuse", value: 1 }
    - { name: "net.netfilter.nf_conntrack_max", value: 524288 }
    - { name: "fs.inotify.max_user_watches", value: 1048576 }
    - { name: "fs.may_detach_mounts", value: 1 }
    - { name: "vm.dirty_background_ratio", value: 5 }
    - { name: "vm.dirty_ratio", value: 10 }
    - { name: "vm.swappiness", value: 0 }
    - { name: "vm.max_map_count", value: 262144 }
