---

- name: Install docker
  hosts: k8s
  roles:
    - docker
  tags: ins-docker

- name: Install kube
  hosts: k8s
  roles:
    - ins-kube
  tags: ins-kube

- name: Init First
  vars_prompt:
    name: "reset"
    prompt: "Do you reset etc before init master(y/n)"
  hosts: master[0]
  tasks:
    - name: Reset conf
      shell: "kubeadm reset -f"
      when: "reset == 'y'"
    - name: Ensure docker
      systemd:
        name: docker
        enabled: yes
        daemon_reload: yes
        state: started
    - name: Init k8s master
      shell: "sudo kubeadm init --kubernetes-version {{ K8S_VERSION }} --control-plane-endpoint {{ LOAD_BALANCER_VIP }}:{{ LOAD_BALANCER_PORT }} --upload-certs"

