---

- name: Install kube
  hosts: k8s
  roles:
    - ins-kube
  tags: ins-kube

- name: Install etcd
  hosts: k8s
  roles:
    - kube-etcd
  tags: kube-etcd

- name: Init First
  host: k8s-master[0]
  roles:
    - master-init
