---

- name: Install cni
  shell: |
    mkdir -p /opt/cni/bin
    mkdir -p /opt/bin
    curl -L "https://github.com/containernetworking/plugins/releases/download/{{ CNI_VERSION }}/cni-plugins-linux-amd64-{{ CNI_VERSION }}.tgz" | tar -C /opt/cni/bin -xz
    curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ CRICTL_VERSION }}/crictl-{{ CRICTL_VERSION }}-linux-amd64.tar.gz" | tar -C /opt/bin -xz

- name: Get stable release
  shell: "curl -sSL https://dl.k8s.io/release/stable.txt"
  register: RELEASE

- name: systemd
  shell: |
    curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/{{ RELEASE }}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
    chmod +x {kubeadm,kubelet,kubectl}
    curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ RELEASE }}/build/debs/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
    mkdir -p /etc/systemd/system/kubelet.service.d
    curl -sSL "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ RELEASE }}/build/debs/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    systemctl enable --now kubelet
  args:
    chdir: /opt/bin